name: Deployment Laravel

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-20.04 
    needs: laravel-tests

steps:
  - name: Deploy to VPS
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      password: ${{ secrets.SSH_PASSWORD }}
      port: 22
      script: |
        cd /home/yusufprog/apps/etrans-api
        git pull origin master
        git status
        docker-compose run --rm php php artisan config:cache
        docker-compose run --rm php php artisan route:cache
        docker-compose run --rm php php artisan view:cache
        docker-compose down
        docker-compose up -d
